version: "3"
services:
  db:
    image: postgres:14.0
    container_name: postgres-server
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "mydatabase"
