FROM amd64/python:3.9-slim

RUN apt-get update && apt-get install -y \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/app
COPY . /usr/app

RUN pip install -U pip &&\
    pip install scikit-learn pandas psycopg2-binary

ENV PYTHONPATH /usr/app

ENTRYPOINT ["python", "main.py"]