FROM amd64/python:3.9-slim

RUN apt-get update && apt-get install -y \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/app

ENV PYTHONPATH "${PYTHONPATH}:/usr/app"
ENV PYTHONUNBUFFERED 1

RUN pip install -U pip &&\
    pip install scikit-learn pandas psycopg2-binary

COPY database/mlops_insert_iris_data.py database/mlops_insert_iris_data.py

ENTRYPOINT ["python", "database/mlops_insert_iris_data.py", "--db-host"]
# Change CMD to solve host finding error
CMD ["localhost"]